services:
  app:
    build:
      context: .
      args:
        - DEV=true
        - SECRET_KEY=django-insecure-w1!)bg04sxez7q_36bsg2g0!tc8y4s2u*zcb6!^_ds%sft@&jv
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: alx_project_nexus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    env_file:
      - .env

  redis:
    image: redis:7-alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  celery:
    build:
      context: .
      args:
        - DEV=true
        - SECRET_KEY=django-insecure-w1!)bg04sxez7q_36bsg2g0!tc8y4s2u*zcb6!^_ds%sft@&jv
    command: celery -A app worker -l info
    volumes:
      - .:/app
    env_file:
      - .env.docker
    depends_on:
      - rabbitmq

volumes:
  dev-db-data:
