services:
  app:
    build:
      context: .
      args:
        - DEV=false
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: >
      sh -c "python manage.py migrate &&
             gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq

  db:
    image: postgres:15-alpine
    volumes:
      - prod-db-data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7-alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  celery:
    build: .
    command: celery -A app worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - rabbitmq

volumes:
  prod-db-data:
  static_volume:
  media_volume:
